[project]
name = "ehrenreich-ml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "einops>=0.8.1",
    "librosa>=0.11.0",
    "pandas>=2.3.3",
    "torch>=2.9.1",
    "tqdm>=4.67.1",
]
